//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CircleProgressBar.h"

@interface CircleProgressBar (Private)
- (void)updateProgressBarForAnimation;
- (void)animateProgressBarChangeFrom:(double)arg1 to:(double)arg2 duration:(double)arg3;
- (void)drawHint:(struct CGContext *)arg1 center:(struct CGPoint)arg2 radius:(double)arg3;
- (void)drawAttributedHintTextAtCenter:(struct CGPoint)arg1;
- (void)drawSimpleHintTextAtCenter:(struct CGPoint)arg1;
- (id)stringRepresentationOfProgress:(double)arg1;
- (id)hintTextColorForDrawing;
- (id)hintTextFontForDrawing;
- (id)hintViewBackgroundColorForDrawing;
- (double)hintViewSpacingForDrawing;
- (void)drawProgressBar:(struct CGContext *)arg1 progressAngle:(double)arg2 center:(struct CGPoint)arg3 radius:(double)arg4;
- (double)progressBarWidthForDrawing;
- (id)progressBarTrackColorForDrawing;
- (id)progressBarProgressColorForDrawing;
- (void)drawBackground:(struct CGContext *)arg1;
- (double)progressAccordingToBounds:(double)arg1;
@end

