//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ICdnComMgrExt.h"

@class CdnTaskInfo, NSMutableArray, NSMutableDictionary, NSString;

@interface DownloadVideoCDNMgr : NSObject <ICdnComMgrExt>
{
    NSMutableArray *_arrDownloadTask;
    CdnTaskInfo *_curTaskInfo;
    NSMutableDictionary *m_dicDownloadVideoCache;
}

- (void).cxx_destruct;
- (void)OnCdnDownload:(id)arg1;
- (void)OnCdnDownloadProgress:(id)arg1;
- (void)OnSetCdnDnsInfo;
- (void)Stop;
- (void)StopDownloadByChatName:(id)arg1;
- (void)StopDownload:(id)arg1 Result:(struct CDNDownloadResult *)arg2;
- (void)StopDownload:(id)arg1;
- (void)StopCurDownload;
- (void)StopCurDownload:(struct CDNDownloadResult *)arg1;
- (_Bool)StartDownloadVideo:(id)arg1 AutoDownload:(_Bool)arg2 Priority:(_Bool)arg3;
- (_Bool)StartDownloadVideo:(id)arg1 AutoDownload:(_Bool)arg2;
- (_Bool)IsMsgInDownloadQueue:(id)arg1;
- (void)CheckQueue;
- (_Bool)CheckForLocalCache:(id)arg1;
- (void)DelTaskInDownloadQueue:(id)arg1;
- (void)videoKVReport:(id)arg1;
- (void)DownloadFail:(int)arg1 oDownloadInfo:(id)arg2;
- (void)DownloadOk;
- (void)RemoveCacheByLRU;
- (void)SaveCacheData;
- (void)LoadCacheData;
- (id)GetVideoCachePath;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

