//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IVideoPlayerCoreDelegate.h"
#import "WCNetworkMediaCoreDelegate.h"

@class MMProgressViewEx, MMTimer, MMUIButton, MMUILabel, MMVideoPlayerCore, MMWebImageView, NSString, UIButton, UILabel, WAWebViewController, WCNetworkMediaCore, WCNetworkMediaSlider;

@interface MMStreamPlayerView : UIView <WCNetworkMediaCoreDelegate, IVideoPlayerCoreDelegate>
{
    int retryCount;
    id <MMVideoPlayerViewDelegate> _videoDelagate;
    WAWebViewController *_webViewController;
    NSString *_path;
    NSString *_thumb;
    WCNetworkMediaCore *_mediaCore;
    MMVideoPlayerCore *_movieCore;
    UIView *_bottomView;
    MMUILabel *_currentLabel;
    WCNetworkMediaSlider *_progressSlider;
    MMUILabel *_durationLabel;
    UIButton *_playBtn;
    UIButton *_fullBtn;
    MMProgressViewEx *_loadingView;
    MMTimer *_timer;
    UIView *_coverView;
    UILabel *_coverTime;
    MMWebImageView *_thumbImage;
    MMUIButton *_coverButton;
    struct CGSize _videoSize;
    struct CGRect _rect;
}

@property(retain, nonatomic) MMUIButton *coverButton; // @synthesize coverButton=_coverButton;
@property(retain, nonatomic) MMWebImageView *thumbImage; // @synthesize thumbImage=_thumbImage;
@property(retain, nonatomic) UILabel *coverTime; // @synthesize coverTime=_coverTime;
@property(retain, nonatomic) UIView *coverView; // @synthesize coverView=_coverView;
@property(retain, nonatomic) MMTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) MMProgressViewEx *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIButton *fullBtn; // @synthesize fullBtn=_fullBtn;
@property(retain, nonatomic) UIButton *playBtn; // @synthesize playBtn=_playBtn;
@property(retain, nonatomic) MMUILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(retain, nonatomic) WCNetworkMediaSlider *progressSlider; // @synthesize progressSlider=_progressSlider;
@property(retain, nonatomic) MMUILabel *currentLabel; // @synthesize currentLabel=_currentLabel;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) struct CGRect rect; // @synthesize rect=_rect;
@property(nonatomic) struct CGSize videoSize; // @synthesize videoSize=_videoSize;
@property(retain, nonatomic) MMVideoPlayerCore *movieCore; // @synthesize movieCore=_movieCore;
@property(retain, nonatomic) WCNetworkMediaCore *mediaCore; // @synthesize mediaCore=_mediaCore;
@property(copy, nonatomic) NSString *thumb; // @synthesize thumb=_thumb;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(nonatomic) __weak WAWebViewController *webViewController; // @synthesize webViewController=_webViewController;
@property(nonatomic) __weak id <MMVideoPlayerViewDelegate> videoDelagate; // @synthesize videoDelagate=_videoDelagate;
- (void).cxx_destruct;
- (void)onVideoEnd;
- (void)onVideoUpdate:(CDStruct_1b6d18a9)arg1 total:(CDStruct_1b6d18a9)arg2;
- (void)onVideoReady:(id)arg1;
- (void)setVideoThumbImage:(id)arg1;
- (void)resizeThumbImage;
- (void)onMediaCore:(id)arg1 VideoSizeUpdate:(struct CGSize)arg2;
- (void)onMediaCore:(id)arg1 DarutionUpdate:(double)arg2;
- (void)onMediaCore:(id)arg1 CacheDarutionChange:(double)arg2;
- (void)onMediaCore:(id)arg1 StateChange:(int)arg2;
- (void)onFullClick;
- (void)disableFull;
- (void)enableFull;
- (void)pause;
- (void)play:(_Bool)arg1;
- (void)onLargePlay;
- (void)onPlayClick;
- (void)onSliderChange;
- (void)updateVideoFrame;
- (void)retryToLoadVideo;
- (void)hideControlViews;
- (void)showControlViews;
- (void)catchTap:(id)arg1;
- (void)refreshCurrentTime;
- (id)timeFormat:(int)arg1;
- (void)updateSubviews:(struct CGSize)arg1;
- (void)setVideoFrame:(struct CGRect)arg1;
- (void)initMediaCore;
- (void)setVideoPath:(id)arg1;
- (void)setVideoThumb:(id)arg1;
- (void)dealloc;
- (id)initWithThumb:(id)arg1 frame:(struct CGRect)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

