//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (Swizzle)
+ (void)load;
- (id)mmInitWithObjects:(id)arg1 forKeys:(id)arg2;
- (id)mmObjectForKeyedSubscript:(id)arg1;
@end

