//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QAnnotationView.h"

@interface QAnnotationView (Private)
- (void)notifyCalloutAccessoryControlTapped:(id)arg1;
- (void)notifyDidChangeDragState:(int)arg1 fromOldState:(int)arg2;
- (void)notifyDidDeselect;
- (void)notifyDidSelect;
- (CDStruct_c3b9c2ee)coordinateForPoint:(struct CGPoint)arg1;
- (void)updateCenter;
- (id)container;
- (id)mapView;
- (id)annotationFloor;
@end

