//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QuartzObject.h"

@class NSArray;

@interface QuartzDrawPath : QuartzObject
{
    _Bool _fill;
    NSArray *_path;
}

@property(retain, nonatomic) NSArray *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (void)arcTo:(struct CGContext *)arg1 data:(id)arg2;
- (void)arc:(struct CGContext *)arg1 data:(id)arg2;
- (void)bezierCurveTo:(struct CGContext *)arg1 data:(id)arg2;
- (void)quadraticCurveTo:(struct CGContext *)arg1 data:(id)arg2;
- (void)rect:(struct CGContext *)arg1 data:(id)arg2;
- (void)closePath:(struct CGContext *)arg1 data:(id)arg2;
- (void)lineTo:(struct CGContext *)arg1 data:(id)arg2;
- (void)moveTo:(struct CGContext *)arg1 data:(id)arg2;
- (void)drawPath:(struct CGContext *)arg1;
- (void)Execute:(struct CGContext *)arg1;
- (id)initWithPath:(id)arg1 fill:(_Bool)arg2;

@end

