//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SightPlayerView.h"

#import "AVAssetResourceLoaderDelegate.h"
#import "WCAVPlayerDataMrgExt.h"

@class CdnDownloadTaskInfo, NSArray, NSMutableDictionary, NSObject, NSString, NSURL;

@interface VideoPlayView : SightPlayerView <AVAssetResourceLoaderDelegate, WCAVPlayerDataMrgExt>
{
    NSObject *playbackTimeObserver;
    unsigned int loadingRequestNum;
    _Bool isBuffering;
    NSArray *m_BufferArray;
    unsigned int m_uBufferCount;
    unsigned int m_uSeekTime;
    _Bool m_bForcePause;
    _Bool m_bGetMoov;
    unsigned int m_uMemoryForSeekTime;
    unsigned int preloadSec;
    double onStartPlayTime;
    double bufferTotalTime;
    _Bool m_bLeavePlayerPage;
    CdnDownloadTaskInfo *oCdnDownloadTaskInfo;
    unsigned int _playedDuration;
    unsigned int _playedSec;
    float _downloadOnceTime;
    id <NSObject><AVPlayerStateControlDelegate> _controlDelegate;
    NSMutableDictionary *_resourceLoaders;
    NSURL *_currentURL;
}

@property(nonatomic) float downloadOnceTime; // @synthesize downloadOnceTime=_downloadOnceTime;
@property(nonatomic) unsigned int playedSec; // @synthesize playedSec=_playedSec;
@property(nonatomic) unsigned int playedDuration; // @synthesize playedDuration=_playedDuration;
@property(retain, nonatomic) NSURL *currentURL; // @synthesize currentURL=_currentURL;
@property(retain, nonatomic) NSMutableDictionary *resourceLoaders; // @synthesize resourceLoaders=_resourceLoaders;
@property(nonatomic) __weak id <NSObject><AVPlayerStateControlDelegate> controlDelegate; // @synthesize controlDelegate=_controlDelegate;
- (void).cxx_destruct;
- (void)notifyToNeedCheckPlayState:(id)arg1;
- (void)onRecievedFristPartAVData:(id)arg1;
- (void)onDownloadToEnd:(id)arg1;
- (void)OnCdnDownloadVideoFail:(id)arg1;
- (void)OnCdnDownloadVideoSuccess:(id)arg1;
- (void)OnDownloadError:(id)arg1;
- (void)resourceLoader:(id)arg1 didCancelLoadingRequest:(id)arg2;
- (_Bool)resourceLoader:(id)arg1 shouldWaitForLoadingOfRequestedResource:(id)arg2;
- (void)reportKVArgs:(struct CDNDownloadResult)arg1;
- (unsigned int)getCurrentSeconde;
- (double)getBufferTime;
- (void)calculateDownloadProgress;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)monitoringPlayback:(id)arg1;
- (void)addOneSliceTimeDownloadTask;
- (void)updateVideoTime;
- (void)pauseForLoading;
- (void)startBuffering;
- (void)resumeToPlay;
- (void)seekTo:(unsigned int)arg1;
- (void)pausePlayer;
- (void)pauseForce:(_Bool)arg1;
- (void)startPlayer;
- (void)playToEnd:(id)arg1;
- (void)clearBufferCountAndPlayedTime;
- (void)savePlayedTimeToMemory;
- (id)buildAVItem;
- (void)initPlayer;
- (void)clearPlayer;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

