//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VOIPCSSyncMgr.h"

@interface VOIPCSSyncMgr (SendRequest)
- (void)SendCSSyncRequestFor:(id)arg1 withSelector:(unsigned int)arg2;
- (void)SendSyncRequestFor:(id)arg1 withSelector:(unsigned int)arg2;
@end

