//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WAAppTaskLoaderDelegate.h"
#import "WAJSCoreServiceDelegate.h"
#import "WAWebViewDelegate.h"

@class CContact, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, WAAppTaskLoader, WAJSCoreService, WAPermissionHandler, WAWebViewController;

@interface WAAppTask : NSObject <WAAppTaskLoaderDelegate, WAWebViewDelegate, WAJSCoreServiceDelegate>
{
    NSString *_appID;
    CContact *_contact;
    NSString *_relativeURL;
    unsigned int _debugModeType;
    NSDictionary *_dicExtraInfo;
    NSMutableArray *_arrWebView;
    NSMutableDictionary *_dicTabWebView;
    WAWebViewController *_preloadWebView;
    WAJSCoreService *_appService;
    _Bool _isWriteFrameContentCache;
    WAWebViewController *_curAppRouteWebView;
    _Bool _isForeground;
    _Bool _isPopParent;
    unsigned int _webViewMaxDepth;
    unsigned int _backgroundTaskMaxTimeout;
    NSString *_refererHost;
    unsigned int _timeEnterBackground;
    id <WAAppTaskDelegate> delegate;
    WAAppTaskLoader *_appLoader;
    WAPermissionHandler *_permissionHandler;
}

@property(retain) WAPermissionHandler *permissionHandler; // @synthesize permissionHandler=_permissionHandler;
@property(retain, nonatomic) WAAppTaskLoader *appLoader; // @synthesize appLoader=_appLoader;
@property(nonatomic) unsigned int timeEnterBackground; // @synthesize timeEnterBackground=_timeEnterBackground;
@property(nonatomic) __weak id <WAAppTaskDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)printConsoleLog:(id)arg1;
- (id)GetWeAppPluginByName:(id)arg1;
- (void)resetTask;
- (void)closeTask;
- (_Bool)isTaskRunning;
- (void)enterBackground;
- (_Bool)isFirstWebViewOnForeground;
- (void)checkForegound;
- (void)leaveForeground;
- (void)enterForeground;
- (_Bool)isForeground;
- (_Bool)hasPermissionWithJSAPI:(id)arg1 fromAppService:(id)arg2;
- (void)setAppServiceCurrentWebView:(id)arg1;
- (void)appServiceSendOnEnterBackground;
- (void)appServiceSendOnEnterForeground;
- (id)getStrForOpenType:(unsigned long long)arg1 webviewID:(unsigned long long)arg2;
- (void)sendAppRouteEventFromWebView:(id)arg1 openType:(unsigned long long)arg2;
- (void)setupAppServiceWithContact:(id)arg1;
- (void)clearAppService;
- (void)sendJSEventToService:(id)arg1 param:(id)arg2 fromWebView:(id)arg3;
- (void)publishPostMessage:(id)arg1 fromWebView:(id)arg2;
- (_Bool)checkWebViewRunMode:(id)arg1;
- (_Bool)checkServiceRunMode:(id)arg1;
- (_Bool)hasPermissionWithJSAPI:(id)arg1 fromWebView:(id)arg2;
- (void)webView:(id)arg1 didLoadFrameContent:(id)arg2;
- (id)askFrameContentFromWebView:(id)arg1;
- (_Bool)webViewIsSameDepthWithFirstPage:(id)arg1;
- (_Bool)webViewIsFirstPage:(id)arg1;
- (void)killAppFrom:(id)arg1 animate:(_Bool)arg2;
- (void)enterBackgroundFrom:(id)arg1 animate:(_Bool)arg2;
- (void)popToFirstWebViewFrom:(id)arg1;
- (void)webViewDidSwitchTab:(id)arg1;
- (id)getPreviousWebViewFromWebView:(id)arg1;
- (id)getTabChildWebViewWithRelativeURL:(id)arg1 fromWebView:(id)arg2;
- (void)webViewOnBeforeEveluateIndexData:(id)arg1;
- (void)webViewDidBePoped:(id)arg1;
- (void)webViewDidDisappear:(id)arg1;
- (void)webViewDidAppear:(id)arg1 notCallOnAppRoute:(_Bool)arg2;
- (void)saveFrameContentCache:(id)arg1;
- (id)loadFrameContentCache;
- (id)frameContentCachePath;
- (id)getAndDeletePreLoadWebView;
- (void)setupPreloadWebViewFromWebView:(id)arg1;
- (void)updateAllWebViewExtraInfo:(id)arg1;
- (id)generateExtraInfoWithAppID:(id)arg1 Contact:(id)arg2 inputExtraInfo:(id)arg3;
- (id)getTabChildWebViewWithRelativeURL:(id)arg1 fromParentWebView:(id)arg2;
- (id)getChildWebViewWithRelativeURL:(id)arg1 childExtraInfo:(id)arg2 fromParentWebView:(id)arg3;
- (id)getNewWebViewControllerWithContact:(id)arg1 appID:(id)arg2 baseURL:(id)arg3 pageRelativeURL:(id)arg4;
- (void)clearTabWebView;
- (void)removeTabWebViewWithParentWebView:(id)arg1;
- (void)addTabWebView:(id)arg1 parentWebView:(id)arg2;
- (void)clearWebView;
- (void)popWebView:(id)arg1;
- (void)removeWebView:(id)arg1;
- (void)addWebView:(id)arg1;
- (void)closePresentViewController;
- (void)removeWebViewFromNavigationController:(_Bool)arg1;
- (void)showWebViewFromBackground:(id)arg1;
- (unsigned int)webViewDepth;
- (_Bool)loadAppConfig:(id)arg1;
- (void)setupAppConfig;
- (void)removeParentWebView:(id)arg1;
- (void)removeChildWebView:(id)arg1 fromParentWebView:(id)arg2;
- (void)getChildWebView:(id *)arg1 withRelativeURL:(id)arg2 childExtraInfo:(id)arg3 fromParentWebView:(id)arg4;
- (void)setupAppServiceAndWebViewWithAppID:(id)arg1 contact:(id)arg2 baseURL:(id)arg3 pageRelativeURL:(id)arg4 getWebView:(id *)arg5;
- (void)resetAppLoader;
- (_Bool)isLoading;
- (id)getAllWebViews;
- (void)sendJSEventToWebView:(id)arg1 param:(id)arg2 toWebviews:(id)arg3;
- (void)openChildWebViewWithRelativeURL:(id)arg1 childExtraInfo:(id)arg2 fromParent:(id)arg3 isPopParent:(_Bool)arg4 errorHandler:(CDUnknownBlockType)arg5;
- (void)openWithContact:(id)arg1 relativeURL:(id)arg2 extraInfo:(id)arg3 navigationController:(id)arg4 errorHandler:(CDUnknownBlockType)arg5;
- (unsigned int)backgroundTaskMaxTimeout;
- (_Bool)isShowOnForeground;
- (unsigned long long)webViewInNavigationCount;
- (unsigned int)debugModeType;
- (id)relativeURL;
- (id)contact;
- (id)appID;
- (void)dealloc;
- (id)initWithAppID:(id)arg1 debugModeType:(unsigned int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

