//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface WAAppHistoryMagager : MMService <MMService>
{
    NSMutableArray *m_historyItems;
    NSMutableDictionary *m_imageDict;
}

+ (id)genCornerImage:(id)arg1;
- (void).cxx_destruct;
- (id)genWebViewSnapImagePath:(id)arg1;
- (id)sessionidInHistory:(id)arg1;
- (void)deleteAppItemInHistory:(id)arg1;
- (id)getAllAppItems;
- (unsigned long long)itemCount;
- (id)itemAtIndex:(unsigned long long)arg1;
- (_Bool)isAppItemInHistory:(id)arg1;
- (void)fetchImageSuccess:(CDUnknownBlockType)arg1;
- (void)saveSnapWithWebView:(id)arg1 forceUpdate:(_Bool)arg2;
- (void)saveSnapWithWebView:(id)arg1;
- (void)initData;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

