//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface WAAppDebugItem : MMObject
{
    unsigned int _type;
    unsigned int _debugStartTime;
    unsigned int _debugEndTime;
    NSString *_appid;
    NSString *_username;
    NSString *_debugURL;
}

@property(nonatomic) unsigned int debugEndTime; // @synthesize debugEndTime=_debugEndTime;
@property(nonatomic) unsigned int debugStartTime; // @synthesize debugStartTime=_debugStartTime;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *debugURL; // @synthesize debugURL=_debugURL;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *appid; // @synthesize appid=_appid;
- (void).cxx_destruct;
- (id)toXML;
- (_Bool)fromXMLStr:(id)arg1;
- (_Bool)fromXML:(struct XmlReaderNode_t *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

