//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMsgExt.h"
#import "MMService.h"

@class NSDictionary, NSMutableDictionary, NSString, WAAppBrandNotifyStorage;

@interface WAConfigMgr : MMService <IMsgExt, MMService>
{
    NSMutableDictionary *_dicAppID2ConfigJSON;
    NSMutableDictionary *_dicAppID2ContactAttribute;
    WAAppBrandNotifyStorage *m_notifyStorage;
    NSMutableDictionary *dicUseVConsoleApp;
    NSDictionary *_dicSystemConfig;
    NSString *_mmUserAgent;
}

+ (_Bool)isOpenFindFriendEntry;
@property(retain) NSString *mmUserAgent; // @synthesize mmUserAgent=_mmUserAgent;
@property(retain) NSDictionary *dicSystemConfig; // @synthesize dicSystemConfig=_dicSystemConfig;
- (void).cxx_destruct;
- (id)waappBanSceneWithAppid:(id)arg1 banScene:(unsigned long long)arg2;
- (id)waappDetailInfoViewURLWithAppid:(id)arg1;
- (id)lowVersionWithAppid:(id)arg1;
- (id)forbbidenUrlWithAppid:(id)arg1;
- (id)exposeURLWithAppid:(id)arg1 msgid:(id)arg2;
- (id)exposeURLWithAppid:(id)arg1 pageid:(id)arg2;
- (void)deleteDebugModeAppInfo:(id)arg1;
- (void)insertDeubgModeAppInfo:(id)arg1;
- (void)parseNotifyMsg:(id)arg1;
- (id)getSaveInfoKeyWithAppid:(id)arg1 debugType:(unsigned int)arg2;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)saveNotifyStorage:(id)arg1;
- (void)loadNotifyStorage;
- (void)setDebugModeDownloadPkgCompleteWithAppid:(id)arg1 debugType:(unsigned long long)arg2 value:(_Bool)arg3;
- (_Bool)isDebugModeAlreadyUpdatePkgWithAppid:(id)arg1 debugType:(unsigned long long)arg2;
- (id)getDebugPkgValidTimeStrWithAppid:(id)arg1 debugType:(unsigned long long)arg2;
- (id)getDebugPkgDownloadUrlWithAppid:(id)arg1 debugType:(unsigned long long)arg2;
- (id)getAllDebugModeAppInfoForceSave:(_Bool)arg1;
- (id)getDeubgModeAppInfoByName:(id)arg1;
- (_Bool)isDebugModeAppWithUserName:(id)arg1;
- (id)getAllDebugModeAppInfo;
- (id)getPublicResDebugModeAppInfo;
- (_Bool)closeUseVConsoleWithAppID:(id)arg1;
- (_Bool)openUseVConsoleWithAppID:(id)arg1;
- (_Bool)pageIsUseVConsoleForAppID:(id)arg1;
- (id)getMMUserAgent;
- (void)updateMMUserAgent;
- (id)getAppWebPageFullUrlWithAppid:(id)arg1 version:(unsigned long long)arg2 relativePath:(id)arg3 isDebugMode:(unsigned long long)arg4;
- (id)getCdnBaseUrlStrIsDebugMode:(unsigned long long)arg1;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

