//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface WAConfigSystemSetting : NSObject
{
    NSDictionary *_dicSetting;
}

- (void).cxx_destruct;
- (id)httpSetting;
- (unsigned int)defaultAppMaxRunningCount;
- (unsigned int)appMaxRunningCount;
- (id)defaultCDNBaseURL;
- (id)cdnBaseURL;
- (unsigned int)defaultAppServiceMaxDataSize;
- (unsigned int)appServiceMaxDataSize;
- (unsigned int)downloadFileMaxTimeoutMS;
- (unsigned int)uploadFileMaxTimeoutMS;
- (unsigned int)webSocketMaxTimeoutMS;
- (unsigned int)requestMaxTimeoutMS;
- (id)defaultHttpHeaderReferer;
- (id)httpHeaderReferer;
- (id)httpHeaderWhiteList;
- (id)httpHeaderBlackList;
- (id)httpHeaderMode;
- (id)initWithSetting:(id)arg1;

@end

