//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WADatabaseMgr.h"

@interface WADatabaseMgr (Contact)
- (_Bool)clearBizAttrSyncBufferList:(id)arg1;
- (_Bool)setBizAttrSyncBufferList:(id)arg1;
- (id)getBizAttrSyncBuffer:(id)arg1;
- (id)dbContactWithContact:(id)arg1;
- (id)contactFromDBContact:(id)arg1;
- (_Bool)modifyWxAppOpt:(id)arg1 bitMask:(unsigned int)arg2 bitValue:(unsigned int)arg3;
- (_Bool)unfocusContact:(id)arg1 getType:(unsigned int *)arg2;
- (_Bool)unfocusContact:(id)arg1;
- (_Bool)focusContact:(id)arg1;
- (_Bool)deleteContactList:(id)arg1;
- (_Bool)inserOrUpdateContactList:(id)arg1;
- (_Bool)hasContact:(id)arg1;
- (id)getAllNoFocusContact;
- (id)getAllFocusContact;
- (id)getContact:(id)arg1;
@end

