//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewFlowLayout.h"

@class NSIndexPath;

@interface WAEntryBaseViewLayout : UICollectionViewFlowLayout
{
    NSIndexPath *_hideIndexPath;
}

@property(copy, nonatomic) NSIndexPath *hideIndexPath; // @synthesize hideIndexPath=_hideIndexPath;
- (void).cxx_destruct;
- (struct CGSize)collectionViewContentSize;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;

@end

