//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WAFileStorage : NSObject
{
}

+ (unsigned long long)localIDGeneratorIncreaseID;
+ (_Bool)isMD5StringValid:(id)arg1;
+ (_Bool)isFileTypeValid:(id)arg1;
+ (_Bool)generatLocalID:(id *)arg1 path:(id *)arg2 withAppID:(id)arg3 fileType:(id)arg4 fileDir:(id)arg5 localIDPrefix:(id)arg6;
+ (void)saveImageWithAppID:(id)arg1 images:(id)arg2 completeHandler:(CDUnknownBlockType)arg3;
+ (void)saveOriginalImageWithAppID:(id)arg1 asset:(id)arg2 completeHandler:(CDUnknownBlockType)arg3;
+ (_Bool)isTempLocalID:(id)arg1;
+ (id)filePathWithAppID:(id)arg1 localID:(id)arg2;
+ (_Bool)generateStoreLocalID:(id *)arg1 path:(id *)arg2 withAppID:(id)arg3 fileType:(id)arg4;
+ (_Bool)generateTempLocalID:(id *)arg1 path:(id *)arg2 withAppID:(id)arg3 fileType:(id)arg4;
+ (id)fileSchema;

@end

