//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class MMWebImageView, NSString, UIButton, UIImage, UIImageView, UILabel;

@interface WAHistoryCollectionViewCell : UICollectionViewCell
{
    UIImage *_image;
    NSString *_title;
    NSString *_userName;
    NSString *_headUrl;
    long long _mode;
    long long _index;
    id <WAHistoryCollectionCellDelegate> _delegate;
    MMWebImageView *_logoImageView;
    UIImageView *_imageView;
    UILabel *_label;
    UIImageView *_shadowView;
    UIButton *_deleteButton;
}

@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UIImageView *shadowView; // @synthesize shadowView=_shadowView;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) MMWebImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(nonatomic) __weak id <WAHistoryCollectionCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
@property(retain, nonatomic) NSString *headUrl; // @synthesize headUrl=_headUrl;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)deleteButtonDidClick:(id)arg1;
- (void)layoutSubviews;
- (void)onModifyWeAppContact:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

