//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CContact, MMBrandHeadImageView, NSString, UIButton, UILabel;

@interface WAIconHeadView : UIView
{
    id <WAIconHeadViewDelegate> _delegate;
    CContact *_contact;
    UIButton *_exposeButton;
    MMBrandHeadImageView *_iconImageView;
    UILabel *_titleLabel;
    UILabel *_stateLabel;
    NSString *_title;
}

@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UILabel *stateLabel; // @synthesize stateLabel=_stateLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) MMBrandHeadImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIButton *exposeButton; // @synthesize exposeButton=_exposeButton;
@property(nonatomic) __weak CContact *contact; // @synthesize contact=_contact;
@property(nonatomic) __weak id <WAIconHeadViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onExposeBtnClicked:(id)arg1;
- (void)onInfoBtnClicked:(id)arg1;
- (void)initStateLabel;
- (void)initOperateBtn;
- (void)initTitleLabel;
- (void)initIconImageView;
- (void)initExposeButton;
- (id)initWithContact:(id)arg1;

@end

