//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WAJSCoreService;

@protocol WAJSCoreServiceDelegate <NSObject>
- (_Bool)checkServiceRunMode:(NSString *)arg1;
- (_Bool)hasPermissionWithJSAPI:(NSString *)arg1 fromAppService:(WAJSCoreService *)arg2;
@end

