//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WAPathUtility : NSObject
{
}

+ (id)WATemplateMsgInfoFilePath;
+ (id)WADebugNotifyFilePath;
+ (id)WAConfigDir;
+ (id)WAHomeLayoutItemFilePath;
+ (id)WAHomeLayoutOldFilePath;
+ (id)WAHomeDir;
+ (id)WACommonMarkPath;
+ (id)WACommonPath;
+ (id)WASnapAppNamesFilePath;
+ (id)WASnapAppNamesOldFilePath;
+ (id)WASnapShotImageFolder;
+ (id)WASnapShotDir;
+ (id)WAAppTaskDBPathWithAppID:(id)arg1;
+ (id)WADatabasePath;
+ (id)WAFrameContentCachePathWithAppID:(id)arg1;
+ (id)WAAppCacheSandboxDirWithAppID:(id)arg1;
+ (id)WAAppLibrarySandboxDirWithAppID:(id)arg1;
+ (id)WACacheDir;
+ (id)WATmpDir;
+ (id)WALibraryDir;
+ (id)WADocumentDir;

@end

