//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WAPermissionMgrExtension.h"

@class NSData, NSString;

@interface WAPermissionHandler : NSObject <WAPermissionMgrExtension>
{
    NSString *_appID;
    CDUnknownBlockType _downloadCompletionHandler;
    NSData *_permissionBytes;
}

@property(retain) NSData *permissionBytes; // @synthesize permissionBytes=_permissionBytes;
- (void).cxx_destruct;
- (void)onDownloadPermissionBytes:(id)arg1 isSuccess:(_Bool)arg2 errorCode:(int)arg3;
- (void)loadPermissionBytes;
- (_Bool)hasPermissionWithJSAPI:(id)arg1;
- (_Bool)checkRunMode:(id)arg1 onWebview:(_Bool)arg2;
- (void)asyncUpdatePermissionBytes;
- (void)downloadPermissionBytesWithCompletionHandler:(CDUnknownBlockType)arg1;
- (_Bool)hasPermissionBytes;
- (void)dealloc;
- (id)initWithAppID:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

