//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"
#import "WAAppTaskMgrExt.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface WAUploadFileMgr : MMService <WAAppTaskMgrExt, MMService>
{
    NSMutableDictionary *_dicAppID2UploadHandler;
    NSObject<OS_dispatch_queue> *_workerQueue;
}

- (void).cxx_destruct;
- (void)onAppTaskTerminate:(id)arg1;
- (void)clearUploadHandlerWithAppID:(id)arg1;
- (void)clearAllUploadHandler;
- (id)getAndNewUploadHandlerIfNotExistWithAppID:(id)arg1 appVersion:(unsigned long long)arg2;
- (void)uploadFileWithAppID:(id)arg1 appVersion:(unsigned long long)arg2 url:(id)arg3 localID:(id)arg4 fileFieldName:(id)arg5 httpHeaders:(id)arg6 formFields:(id)arg7 completionHandler:(CDUnknownBlockType)arg8;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

