//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAWebViewPlugin_embedView.h"

#import "QMapViewDelegate.h"
#import "SightViewDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface WAWebViewPlugin_EmbedMap : WAWebViewPlugin_embedView <QMapViewDelegate, SightViewDelegate>
{
    NSMutableArray *_allMaps;
    NSMutableDictionary *_allCovers;
    NSMutableDictionary *_allMarkers;
    unsigned int _tagMax;
}

- (void).cxx_destruct;
- (void)setMapScale:(double)arg1 mapId:(unsigned int)arg2;
- (void)setCenterLocation:(CDStruct_c3b9c2ee)arg1 mapId:(unsigned int)arg2;
- (void)dealloc;
- (void)updateMapCovers:(unsigned int)arg1 covers:(id)arg2;
- (void)clearMapCovers:(unsigned int)arg1;
- (_Bool)removeMap:(unsigned int)arg1;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)didRotate:(id)arg1;
- (_Bool)insertMap:(id)arg1 result:(id *)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

