//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAWebViewController.h"

#import "ForwardMessageLogicDelegate.h"
#import "MMTipsViewControllerDelegate.h"
#import "WAIconActionSheetDelegate.h"
#import "WAQuickAddWebViewBannerDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WCCommitViewResultDelegate.h"

@class NSString;

@interface WAWebViewController (MenuAction) <WAIconActionSheetDelegate, ForwardMessageLogicDelegate, WAQuickAddWebViewBannerDelegate, WCCommitViewResultDelegate, MMTipsViewControllerDelegate, WCActionSheetDelegate>
- (void)goToDestopWithScene:(unsigned long long)arg1;
- (void)showAddContactDisableTips;
- (void)showShareDisableTips;
- (void)showFuntionForbbidenTips;
- (_Bool)checkContactAndShowErrorTipsIfNeeded:(unsigned long long)arg1;
- (id)pluginReportPageEvent;
- (void)onCancelForwardForForwardView:(id)arg1;
- (void)onDoneForwardForForwardView:(id)arg1;
- (void)OnForwardMessageException:(id)arg1;
- (void)OnForwardMessageCancel:(id)arg1;
- (void)OnForwardMessageSend:(id)arg1;
- (void)shareToTimelineWithAppInfo:(id)arg1;
- (void)addFavorItemWithInfo:(id)arg1;
- (void)forwardToFriendWithInfo:(id)arg1;
- (void)addAppContact;
- (void)getWeAppMessageWithActionType:(unsigned long long)arg1 finishBlock:(CDUnknownBlockType)arg2;
- (void)onFocusWeAppContactWithUserName:(id)arg1 errorCode:(int)arg2 errMsg:(id)arg3;
- (id)getCurrentViewController;
- (void)onClickTipsBtn:(id)arg1 Index:(long long)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onWAEntryHomeClicked;
- (void)onWAActionSheetDismiss;
- (void)onAddContact;
- (void)onWAActionSheetExposeClicked;
- (void)onWAActionSheetDestruct;
- (void)onWAActionSheetInfoClicked;
- (void)onWAActionSheetClickButtonWithButtonTitle:(id)arg1;
- (void)commonShare;
- (void)onCloseVConsole;
- (void)onOpenVConsole;
- (void)expose;
- (void)openBrandProfile;
- (void)closeAppPage;
- (void)killApp;
- (void)shareTimeLine;
- (void)addFavor;
- (void)shareToMyFriend;
- (id)menubuttonTitleArray;
- (void)onMenuShow;
- (void)onQuickAddSelected;
- (void)showQuickAddContactBanner;
- (_Bool)shouldShowQuickAddBanner;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

