//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAWebViewController.h"

#import "WAWebErrorViewDelegate.h"

@class NSString;

@interface WAWebViewController (UI) <WAWebErrorViewDelegate>
- (void)saveWebViewSnapshotImageByForceUpdate:(_Bool)arg1;
- (id)snapShotWebviewImage;
- (id)getTabSelectedWebView;
- (void)onWAWebErrorViewOperateBtnClick:(id)arg1;
- (void)show404ErrorView;
- (void)addBackInfoViewIndicator:(id)arg1;
- (id)getBackInfoViewWithAppId:(id)arg1 enablePullRefresh:(_Bool)arg2;
- (_Bool)isTabBarSelectedOtherTab;
- (void)tabBarDidSwitchTab;
- (id)getChildTabWebViews;
- (id)getTabChildWebViewWithRelativeURL:(id)arg1;
- (void)setFullScreenNavAlpha:(id)arg1;
- (void)setTailBackGroundColor:(id)arg1;
- (void)setFullScreen:(_Bool)arg1;
- (void)enableFullScreen;
- (void)restoreToDefaultNavBar;
- (void)setNavBarBgColor:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

