//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WAWebLocalStorage : NSObject
{
}

+ (unsigned long long)maxStorageLengthWithAppID:(id)arg1;
+ (void)clearDataWithAppID:(id)arg1;
+ (_Bool)setData:(id)arg1 dataType:(id)arg2 withKey:(id)arg3 appID:(id)arg4 getError:(id *)arg5;
+ (void)getData:(id *)arg1 dataType:(id *)arg2 withKey:(id)arg3 appID:(id)arg4;

@end

