//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCAVPlayerDataMrgExt.h"

@class CMessageWrap, NSMutableArray, NSString;

@interface WCAVAssetResourceLoader : NSObject <WCAVPlayerDataMrgExt>
{
    unsigned int preloadSec;
    _Bool _m_bDownload;
    unsigned int _preloadingLength;
    CMessageWrap *_m_oMessageWrap;
    NSMutableArray *_pendingRequests;
    NSMutableArray *_downloadTaskArray;
    NSString *_videoPath;
}

@property(nonatomic) _Bool m_bDownload; // @synthesize m_bDownload=_m_bDownload;
@property(retain, nonatomic) NSString *videoPath; // @synthesize videoPath=_videoPath;
@property(nonatomic) unsigned int preloadingLength; // @synthesize preloadingLength=_preloadingLength;
@property(retain) NSMutableArray *downloadTaskArray; // @synthesize downloadTaskArray=_downloadTaskArray;
@property(retain) NSMutableArray *pendingRequests; // @synthesize pendingRequests=_pendingRequests;
@property(retain, nonatomic) CMessageWrap *m_oMessageWrap; // @synthesize m_oMessageWrap=_m_oMessageWrap;
- (void).cxx_destruct;
- (void)OnCdnDownloadVideoSuccess:(id)arg1;
- (void)onRecievedAVData:(id)arg1 NeedNotifyToPlay:(_Bool)arg2;
- (id)loaderCancelledError;
- (void)removeRequest:(id)arg1;
- (void)cancelAllPendingRequests;
- (void)fillInformationForRequest:(id)arg1;
- (void)checkData:(id)arg1 length:(unsigned long long)arg2;
- (_Bool)respondWithDataForRequest:(id)arg1 offset:(long long)arg2 length:(long long)arg3;
- (void)processPendingRequestsFromOffset:(long long)arg1 length:(long long)arg2;
- (void)addRequest:(id)arg1;
- (void)cleanDownloadTask;
- (void)consumeDownloadTask;
- (void)addWCAVDownloadTaskBySec:(unsigned int)arg1;
- (void)dealloc;
- (id)initWithMsg:(id)arg1 filePath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

