//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "ICdnComMgrExt.h"
#import "MMService.h"

@class CMessageWrap, NSString, WCDownloadTask;

@interface WCAVPlayerDataMgr : MMService <MMService, ICdnComMgrExt>
{
    WCDownloadTask *currentDownloadTask;
    long long m_n64MesSvrID;
    double lastMemoryTime;
    unsigned int playedSec;
    CMessageWrap *m_oCurrentMessageWrap;
    double startDownloadTime;
    double onMoovCalledTime;
    double onGetFristPreDataTime;
    double onClickToStartPlay;
}

- (void).cxx_destruct;
- (void)OnCdnDownload:(id)arg1;
- (void)OnCdnVideoDownloadToEnd:(id)arg1;
- (void)OnCdnVideoMoovReady:(id)arg1;
- (void)OnCdnDownloadPartialData:(id)arg1;
- (void)saveToMemoryPlayTime:(unsigned int)arg1 byMessageWrap:(id)arg2;
- (unsigned int)getMemorySeekTime:(id)arg1;
- (_Bool)StopVideoStreamingDownload:(id)arg1 Result:(struct CDNDownloadResult *)arg2;
- (_Bool)RequestVideoDataByClientMediaID:(id)arg1 offset:(long long)arg2 length:(long long)arg3 durationSec:(int)arg4;
- (_Bool)StartVideoStreamingDownload:(id)arg1 PlayMode:(_Bool)arg2;
- (_Bool)isVideoCacheDataExistByMessageWrap:(id)arg1 offset:(long long)arg2 length:(long long)arg3;
- (_Bool)getVideoDataByMessageWrap:(id)arg1 offset:(long long)arg2 length:(long long)arg3 durationSec:(int)arg4 loadingRequest:(id)arg5;
- (_Bool)getVideoDataByMessageWrap:(id)arg1 offset:(long long)arg2 length:(long long)arg3 durationSec:(int)arg4;
- (id)partialDataForFileAtPath:(id)arg1 offset:(long long)arg2 length:(long long)arg3;
- (void)stopCurrentDownloadTask:(_Bool)arg1;
- (id)getCurrentDownloadTask;
- (void)setNeedCheckPlayState:(_Bool)arg1;
- (void)setCurrentDownloadFinish:(_Bool)arg1;
- (void)clearMonitorArgs;
- (double)getStartDownloadTime;
- (double)getOnGetFristPreDataTime;
- (double)getOnMoovCalledTime;
- (double)getClickTime;
- (void)setClickTime;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

