//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAssetResourceLoadingRequest;

@interface WCAVDownloadTask : NSObject
{
    unsigned int _downloadSec;
    AVAssetResourceLoadingRequest *_loadingRequest;
}

@property(nonatomic) unsigned int downloadSec; // @synthesize downloadSec=_downloadSec;
@property(retain, nonatomic) AVAssetResourceLoadingRequest *loadingRequest; // @synthesize loadingRequest=_loadingRequest;
- (void).cxx_destruct;
- (_Bool)isEqualToLoadingRequest:(id)arg1;

@end

