//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCCanvasCommonUtil : NSObject
{
}

+ (_Bool)isSameIndexPathBetween:(id)arg1 WithIndexPath:(id)arg2;
+ (id)genFowardAdXMLByDataItem:(id)arg1 adXML:(id)arg2;
+ (int)getComponentTypeWithCid:(id)arg1;
+ (unsigned int)getComponentCountInCanvasInfo:(id)arg1;
+ (id)getImage:(id)arg1;
+ (id)duplicate2:(id)arg1;
+ (id)duplicate:(id)arg1;

@end

