//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCDataBase.h"

@interface WCDataBase (Backup)
+ (id)backupPathsFrom:(id)arg1;
- (id)backupPaths;
- (void)clearBackup;
- (_Bool)backup;
- (id)getRestoreInfos;
- (id)accquireRestoreInfos;
- (id)accquireSortedBackupInfos;
@end

