//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSString;

@interface WCDBBackupInfo : NSObject
{
    _Bool _integrity;
    NSDate *_modifiedDate;
    NSString *_path;
    NSArray *_restoreInfos;
}

+ (_Bool)writeRestoreInfos:(id)arg1 withBackupInfo:(id)arg2 didWrite:(_Bool *)arg3;
+ (unsigned int)getChecksum:(id)arg1;
@property(readonly) NSArray *restoreInfos; // @synthesize restoreInfos=_restoreInfos;
@property(readonly) _Bool integrity; // @synthesize integrity=_integrity;
@property(readonly) NSString *path; // @synthesize path=_path;
@property(readonly) NSDate *modifiedDate; // @synthesize modifiedDate=_modifiedDate;
- (void).cxx_destruct;
- (_Bool)accquireRestoreInfos;
- (id)initWithPath:(id)arg1;

@end

